New Faction/Trader Accesses
ekrixi-14/ekrixi pull request #152
Opened 2023-09-18 22:57 UTC by Blackern5000

I made a bunch of special accesses for the traders and each faction.
There's a regular access and a command access for each faction, including traders, and then a single hostile access for independent ships so they can't be boarded by the players.
I added two trader jobs (Station Administrator and Trade Technician) who have the new trader accesses but I don't know how to make them spawn instead of the QM at trade stations so I'll let you do that.
I made eight IncSek airlocks, eight Coregov airlocks, four trader airlocks and two hostile airlocks, these should make breaking into ships with doors harder.

(Don't mind me accidentally adding the musca at the start I got my branches mixed up.)

2023-09-19 01:14 UTC, Blackern5000 commented
unfortunately no longer contains trader jobs as advertised due to it not working for some reason

2023-09-19 12:22 UTC, Just-a-Unity-Dev requested changes
Split the accesses from a single `ekrixi.yml` file to their own faction-specific files

2023-09-19 12:22 UTC, Just-a-Unity-Dev commented on Resources/Prototypes/_FTL/Access/ekrixi.yml
> +  name: id-card-access-level-coregov
This locale doesn't exist?

2023-09-19 12:22 UTC, Just-a-Unity-Dev commented on Resources/Prototypes/_FTL/Access/ekrixi.yml
> +  name: id-card-access-level-coregov
Same goes for the rest of the access levels

2023-09-19 16:51 UTC, Blackern5000 commented
> > Split the accesses from a single `ekrixi.yml` file to their own faction-specific files
> 
> Do you want this done with the airlocks file too?

I did it anyway

2023-09-21 05:24 UTC, Just-a-Unity-Dev commented
sgtm

2023-09-21 05:24 UTC, merged