Shield Generator Wall
ekrixi-14/ekrixi pull request #200
Opened 2023-11-16 09:03 UTC by Blackern5000

Rebrands the shuttle wall as the shield generator wall due to it's reflective properties. Still only has 500 HP and easily breaks when hit by HE or PF rounds. It does however reflect AP rounds away from the ship.

Not buildable by players, so it's an NPC map only thing.

![image](https://github.com/ekrixi-14/ekrixi/assets/140123969/967556cd-00f4-4b6c-9730-d12b1d064412)

"cool shader" not included

2023-11-17 01:29 UTC, Just-a-Unity-Dev commented
Absolutely not, Ekrixi is a game where you are forced to build upon armor layer on armor layer to protect your ship from the hostile ships that may protrude.

2023-11-17 01:29 UTC, Just-a-Unity-Dev requested changes
Above.

2023-11-17 09:52 UTC, Blackern5000 commented
Again, this isn't buildable by players, so this wouldn't be a way to avoid damage without the usual 7 armor layers, but rather a reason to vary your ammunition usage when you encounter it on an enemy.

2023-11-29 07:25 UTC, Just-a-Unity-Dev commented
I do not want shield generator walls in Ekrixi

2023-11-29 07:25 UTC, closed without merging