Fix NPCs not having any clothing
ekrixi-14/ekrixi pull request #316
Opened 2024-07-18 07:48 UTC by Blackern5000

## About the PR
NPCs now have clothing again.
![image](https://github.com/user-attachments/assets/df71be82-34ba-41a7-b0f7-769d05f983c8)

Rejoice.

Also adds unused doctor and engineer NPC loadouts for later.

2024-07-18 07:57 UTC, Blackern5000 commented
Test fails unrelated.

2024-07-18 10:26 UTC, Just-a-Unity-Dev requested changes
There's probably a better way to do this without having duplicated code.

2024-07-18 22:23 UTC, Blackern5000 commented
> There's probably a better way to do this without having duplicated code.

Not that I know of, and with this method it means admins can set people/urists to have this outfit instantly using the set outfit command.

2026-04-02 23:04 UTC, aeoli-fly commented
hey chat any chance of this getting merged?

2026-04-03 00:29 UTC, Blackern5000 commented
> hey chat any chance of this getting merged?

perhap one day....

2026-04-03 05:13 UTC, merged

2026-04-03 05:53 UTC, Blackern5000 commented
ONE DAY!!!! IT HAS COME!!!!

2026-04-03 16:14 UTC, Beridot commented
gamers rejoice.